name: Learning CD
on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      versions:
        description: version of the code
        required: true
jobs:
  deploy:
      runs-on: ubuntu-latest
      permissions: 
        contents: write 
      steps:
        - uses: actions/checkout@v7
        - name: Create GitHub Release
          run: echo "${{inputs.versions}}" 