name: Checkppoint 5
on: 
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Let it not fail
        run: echo "you aint gonna fail"
      - name: This should get skipped
        run: echo "Did this run?"
  report:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Report result
        if: always()
        run: echo "Pipeline finished — check ${{ github.actor }} for details"
 