name: checkpoint 9
on: 
  branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [edge,chrome,brave]
        screen: [desktop,mobile,tablet]
        exclude:
          - browser: edge
            screen: desktop
    steps:
      - uses: actions/checkout@v7
      - run: echo "Testing on ${{ matrix.browser }} / ${{ matrix.screen }}"