name: Checkpoint 7
on:
  push:
    branches: [main]
workflow_dispatch:
  inputs:
    env:
      description: 'just an env'
      required: true
      default: 
permission:
  contents: read
jobs:
  build:
    runs-on: unbuntu-latest
    steps: 
      - name: Check if there is secret or not
        env: 
          CP7_SECRET: ${{secrets.CP7_SECRET}}
          APP_STAGE: staging
        run: | 
          if [ ${#CP7_SECRET} -gt 2 ]; then
            echo "yayy, secret is present"
            echo "APP_STAGE: ${{APP_STAGE}}"
          else
            echo "secret missing or too short"
          fi