name: input-output
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'set an env'
        required: true
        default: 
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.app_version_id.outputs.app_version }}
    steps:
      - id: app_version_id
        run: echo 'app_version=4.1.2' <<  "$GITHUB_OUTPUT"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print the output
        run: |
          echo "output: ${{needs.build.outputs.app_version}}"
          echo "input: ${{ inputs.environment }}"