name: jobs-demo
on: 
  push:
    branches: [main]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v7
        - name: Run the build command
          run: go build .
          run: echo "Building..."
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying"