name: matrix
on:
  push:
    branches: [main]
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome,edge,brave]
        screen: [mobile,tablet,laptop]
        exclude:
          - browser: chrome
            screen: mobile
        include: 
          - browser: helium
            screen: desktop
    steps:
      - uses: actions/checkout@v7
      - run: echo "Testing on ${{ matrix.browser }} / ${{ matrix.screen }}"