name: SHH Secret
on: 
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checking the length of secret
        env: 
        MY_SECRET: ${{secrets.DEMO_SECRET}}
        run: |
          if [ ${#MY_SECRET} -gt 15 ]; then
            echo "yayy, secret is present"
          else
            echo "secret missing or too short"
          fi