name: SHH SECRET
on:
  push:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    env: ${{ secrets.DEMO_SECRET }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checking if the secret is accessible
        if: length(${{ secrets.DEMO_SECRET }}) > 15
        run: echo "yayy"